services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamelist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gamelist
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
    depends_on:
      - db

volumes:
  postgres_data: