spring.datasource.url=jdbc:postgresql://localhost:5432/gamelist
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#jwt
jwt.secret=thisIsMySuperSecretPasswordAndYouWontBeAbleToDecipherIt
jwt.expiration=86400000